spring:
  application:
    name: demo

  datasource:
    url: "jdbc:postgresql://localhost:5432/my_db"
    username: postgres
    password: root
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
